name: Github Action Testing
on: workflow_dispatch


jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        id: python
        with:
          python-version: '3.11.5'

      - name: Setup Cache
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            ~/.cache/pre-commit
            ~/.cache/pip
            key: ${{ runner.os }}-pre-commit-upgrade-security${{ hashFiles('.github/pre-commit-config.yaml') }}

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          python -m pip install pre-commit
          pre-commit --version
        shell: bash
